

-- 1) Nested table type for gift items
CREATE OR REPLACE TYPE gift_item_tab AS TABLE OF VARCHAR2(100);
/
-- 2) GIFT_CATALOG with nested table column
CREATE TABLE gift_catalog (
    gift_id      NUMBER        PRIMARY KEY,
    min_purchase NUMBER        NOT NULL,
    gifts        gift_item_tab
)
NESTED TABLE gifts STORE AS gift_catalog_gifts_nt;
/

-- 3) Sample gift packages
INSERT INTO gift_catalog (gift_id, min_purchase, gifts)
VALUES (1, 100,   gift_item_tab('Stickers', 'Pen Set'));

INSERT INTO gift_catalog (gift_id, min_purchase, gifts)
VALUES (2, 1000,  gift_item_tab('Teddy Bear', 'Mug', 'Perfume Sample'));

INSERT INTO gift_catalog (gift_id, min_purchase, gifts)
VALUES (3, 10000, gift_item_tab('Backpack', 'Thermos Bottle', 'Chocolate Collection'));

COMMIT;



CREATE TABLE customer_rewards (
    reward_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                    PRIMARY KEY,
    customer_email  VARCHAR2(255) NOT NULL,
    gift_id         NUMBER        REFERENCES gift_catalog(gift_id),
    reward_date     DATE          DEFAULT SYSDATE,
    CONSTRAINT fk_customer_rewards_customer
        FOREIGN KEY (customer_email)
        REFERENCES customers(email_address)
);
/


-- Package spec
CREATE OR REPLACE PACKAGE customer_manager AS

  -- 1) public function: total purchase per customer
  FUNCTION get_total_purchase (
    p_customer_id IN customers.customer_id%TYPE
  ) RETURN NUMBER;

  -- 3) public procedure: assign gifts to all customers
  PROCEDURE assign_gifts_to_all;

  -- Part D: public procedure to display sample rewards
  PROCEDURE show_sample_rewards;

END customer_manager;
/

CREATE OR REPLACE PACKAGE BODY customer_manager AS


  FUNCTION choose_gift_package (
    p_total_purchase IN NUMBER
  ) RETURN gift_catalog.gift_id%TYPE IS
    v_gift_id gift_catalog.gift_id%TYPE;
  BEGIN
    SELECT gift_id
    INTO   v_gift_id
    FROM (
      SELECT gift_id, min_purchase
      FROM   gift_catalog
      WHERE  min_purchase <= p_total_purchase
      ORDER BY min_purchase DESC
    )
    WHERE ROWNUM = 1;

    RETURN v_gift_id;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END choose_gift_package;



  FUNCTION get_total_purchase (
    p_customer_id IN customers.customer_id%TYPE
  ) RETURN NUMBER IS
    v_total NUMBER;
  BEGIN
    SELECT NVL(SUM(oi.unit_price * oi.quantity), 0)
    INTO   v_total
    FROM   orders o
           JOIN order_items oi
             ON oi.order_id = o.order_id
    WHERE  o.customer_id  = p_customer_id
    AND    o.order_status = 'COMPLETED';  -- change if your status is different

    RETURN v_total;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 0;
  END get_total_purchase;



  PROCEDURE assign_gifts_to_all IS
    v_total   NUMBER;
    v_gift_id gift_catalog.gift_id%TYPE;
  BEGIN
    FOR c IN (SELECT customer_id, email_address FROM customers) LOOP

      v_total   := get_total_purchase(c.customer_id);
      v_gift_id := choose_gift_package(v_total);

      IF v_gift_id IS NOT NULL THEN
        INSERT INTO customer_rewards (customer_email, gift_id)
        VALUES (c.email_address, v_gift_id);
      END IF;

    END LOOP;

    COMMIT;
  END assign_gifts_to_all;


  PROCEDURE show_sample_rewards IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('EMAIL | GIFT_ID | MIN_PURCHASE | REWARD_DATE');

    FOR rec IN (
      SELECT *
      FROM (
        SELECT
          cr.customer_email,
          cr.gift_id,
          gc.min_purchase,
          cr.reward_date
        FROM   customer_rewards cr
               JOIN gift_catalog gc
                 ON gc.gift_id = cr.gift_id
        ORDER BY cr.reward_id
      )
      WHERE ROWNUM <= 5
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(
        rec.customer_email || ' | ' ||
        rec.gift_id        || ' | ' ||
        rec.min_purchase   || ' | ' ||
        TO_CHAR(rec.reward_date, 'YYYY-MM-DD')
      );
    END LOOP;
  END show_sample_rewards;

END customer_manager;
/

SET SERVEROUTPUT ON;

BEGIN
  customer_manager.assign_gifts_to_all;
  customer_manager.show_sample_rewards;
END;
/
