-- Part B: CUSTOMER_REWARDS table
CREATE TABLE customer_rewards (
    reward_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_email  VARCHAR2(255) NOT NULL,
    gift_id         NUMBER REFERENCES gift_catalog(gift_id),
    reward_date     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_customer_rewards_customer
        FOREIGN KEY (customer_email)
        REFERENCES customers(email_address)
);
/
